#!/usr/bin/env bash

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

LAB_HTTP_PORT_NODE_A="${LAB_HTTP_PORT_NODE_A:-8080}"
LAB_HTTP_PORT_NODE_B="${LAB_HTTP_PORT_NODE_B:-8081}"
LAB_HTTP_PORT_NODE_C="${LAB_HTTP_PORT_NODE_C:-8082}"
LAB_HTTP_PORT_NODE_D="${LAB_HTTP_PORT_NODE_D:-8083}"

LAB_GRPC_PORT_NODE_A="${LAB_GRPC_PORT_NODE_A:-9190}"
LAB_GRPC_PORT_NODE_B="${LAB_GRPC_PORT_NODE_B:-9191}"
LAB_GRPC_PORT_NODE_C="${LAB_GRPC_PORT_NODE_C:-9192}"
LAB_GRPC_PORT_NODE_D="${LAB_GRPC_PORT_NODE_D:-9193}"

LAB_AERON_PORT_NODE_A="${LAB_AERON_PORT_NODE_A:-15090}"
LAB_AERON_PORT_NODE_B="${LAB_AERON_PORT_NODE_B:-15091}"
LAB_AERON_PORT_NODE_C="${LAB_AERON_PORT_NODE_C:-15092}"
LAB_AERON_PORT_NODE_D="${LAB_AERON_PORT_NODE_D:-15093}"

LAB_BINARY_PORT_NODE_A="${LAB_BINARY_PORT_NODE_A:-10080}"
LAB_BINARY_PORT_NODE_B="${LAB_BINARY_PORT_NODE_B:-10081}"
LAB_BINARY_PORT_NODE_C="${LAB_BINARY_PORT_NODE_C:-10082}"
LAB_BINARY_PORT_NODE_D="${LAB_BINARY_PORT_NODE_D:-10083}"

LAB_ZOOKEEPER_PORT="${LAB_ZOOKEEPER_PORT:-2181}"
LAB_NACOS_PORT="${LAB_NACOS_PORT:-8848}"
LAB_TOXIPROXY_PORT="${LAB_TOXIPROXY_PORT:-8474}"
LAB_PROMETHEUS_PORT="${LAB_PROMETHEUS_PORT:-19091}"

lab_http_url_for_node() {
  case "$1" in
    node-a) echo "http://127.0.0.1:${LAB_HTTP_PORT_NODE_A}" ;;
    node-b) echo "http://127.0.0.1:${LAB_HTTP_PORT_NODE_B}" ;;
    node-c) echo "http://127.0.0.1:${LAB_HTTP_PORT_NODE_C}" ;;
    node-d) echo "http://127.0.0.1:${LAB_HTTP_PORT_NODE_D}" ;;
    *) return 1 ;;
  esac
}
